version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./online_shop_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - envs/.env
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    env_file:
      - envs/.env