"""Edit constraint for category_id in item table

Revision ID: 1da4e815a2e9
Revises: 9bcf7d122bc0
Create Date: 2023-02-27 22:18:52.103846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da4e815a2e9'
down_revision = '9bcf7d122bc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_item_category_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'categories', ['item_category_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_item_category_id_fkey', 'items', 'categories', ['item_category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
