"""Added user table

Revision ID: 434c2259ce05
Revises: 1da4e815a2e9
Create Date: 2023-03-04 18:48:02.915140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434c2259ce05'
down_revision = '1da4e815a2e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=True),
    sa.Column('user_name', sa.String(length=90), nullable=False),
    sa.Column('first_name', sa.String(length=90), nullable=True),
    sa.Column('last_name', sa.String(length=90), nullable=True),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
