"""Added item table

Revision ID: 9bcf7d122bc0
Revises: 08ed693f4c8f
Create Date: 2023-02-27 14:59:56.090853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcf7d122bc0'
down_revision = '08ed693f4c8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=True),
    sa.Column('unit_price', sa.FLOAT(precision=8), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('item_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
